### PR TITLE
fix: identity registration default key was using wrong `ContractBounds`

### LINKED ISSUE #486: Cannot create identity due to error: expected encryption key bounds for encryption
Identity create in dash-evo-tool with default settings fails.
dash-evo-tool rev 

Image

In drive logs, I found the following:

{"timestamp":"2026-01-21T14:34:42.991443Z","level":"ERROR","fields":{"message":"Failed to process IdentityCreate state transition (01a458d2b555c9094b5e2d0cd24f682b79e72d85083e4a9a5656a8287c0033fe) : storage: contract: key bounds expected but not present error: expected encryption key bounds for encryption","error":"Drive(DataContract(KeyBoundsExpectedButNotPresent(\"expected encryption key bounds for encryption\")))","raw_state_transition":"[3, 0, 6, 0, 0, 2, 0, 0, 0, 0, 20, 249, 30, 16, 140, 86, 149, 124, 216, 226, 187, 167, 35, 192, 129, 149, 124, 114, 246, 25, 30, 0, 0, 1, 2, 0, 1, 0, 0, 20, 75, 143, 62, 202, 147, 2, 60, 58, 150, 181, 148, 1, 194, 75, 222, 16, 81, 138, 62, 171, 0, 0, 2, 2, 0, 2, 0, 0, 20, 70, 101, 149, 157, 72, 129, 155, 242, 168, 48, 11, 145, 180, 252, 122, 134, 152, 55, 135, 242, 0, 0, 3, 2, 3, 1, 0, 0, 20, 110, 57, 79, 132, 151, 98, 98, 2, 159, 83, 208, 40, 115, 160, 52, 28, 98, 15, 1, 213, 0, 0, 4, 0, 1, 3, 1, 0, 162, 161, 180, 172, 111, 239, 34, 234, 42, 26, 104, 232, 18, 54, 68, 179, 87, 135, 95, 107, 65, 44, 24, 16, 146, 129, 193, 70, 231, 178, 113, 188, 0, 33, 2, 187, 81, 9, 71, 246, 199, 207, 103, 85, 115, 105, 80, 1, 160, 183, 126, 251, 190, 176, 50, 227, 134, 226, 18, 79, 64, 171, 80, 240, 168, 195, 18, 65, 32, 54, 114, 72, 33, 154, 44, 118, 113, 32, 140, 20, 208, 120, 158, 182, 231, 8, 2, 41, 133, 101, 51, 45, 44, 121, 195, 92, 141, 111, 173, 241, 135, 35, 172, 225, 192, 229, 60, 18, 98, 201, 134, 234, 11, 2, 184, 63, 160, 5, 113, 145, 117, 172, 221, 240, 3, 214, 92, 75, 10, 61, 105, 138, 153, 0, 5, 0, 2, 3, 1, 0, 162, 161, 180, 172, 111, 239, 34, 234, 42, 26, 104, 232, 18, 54, 68, 179, 87, 135, 95, 107, 65, 44, 24, 16, 146, 129, 193, 70, 231, 178, 113, 188, 0, 33, 2, 217, 44, 197, 174, 205, 38, 0, 23, 71, 136, 3, 105, 226, 25, 231, 65, 64, 100, 246, 62, 152, 67, 93, 68, 84, 138, 2, 185, 43, 71, 120, 77, 65, 32, 81, 37, 41, 190, 16, 99, 47, 230, 19, 177, 199, 122, 178, 168, 50, 54, 251, 35, 227, 95, 235, 129, 210, 139, 210, 205, 33, 187, 166, 244, 106, 122, 44, 125, 129, 139, 244, 72, 219, 242, 188, 176, 114, 152, 127, 245, 79, 169, 25, 48, 75, 78, 85, 89, 247, 79, 36, 11, 196, 235, 41, 28, 212, 115, 0, 198, 1, 1, 70, 204, 1, 159, 169, 39, 9, 157, 149, 70, 176, 88, 226, 249, 94, 203, 19, 223, 38, 123, 156, 224, 100, 248, 44, 93, 211, 101, 226, 86, 33, 169, 1, 0, 0, 0, 165, 151, 21, 124, 202, 205, 248, 184, 128, 122, 207, 70, 237, 67, 191, 247, 141, 101, 198, 177, 85, 187, 152, 180, 32, 3, 115, 88, 13, 89, 206, 109, 150, 128, 148, 103, 106, 100, 72, 175, 209, 82, 134, 34, 138, 173, 126, 234, 211, 215, 45, 69, 132, 195, 51, 111, 252, 107, 71, 62, 161, 0, 0, 0, 183, 81, 239, 156, 176, 105, 85, 153, 81, 46, 117, 118, 179, 123, 157, 8, 70, 31, 205, 177, 39, 99, 73, 186, 94, 140, 129, 253, 235, 169, 161, 30, 248, 82, 221, 42, 160, 20, 136, 208, 113, 131, 75, 90, 143, 156, 74, 154, 7, 156, 31, 46, 120, 128, 195, 200, 155, 168, 239, 99, 207, 46, 152, 117, 69, 96, 7, 146, 101, 92, 119, 14, 252, 103, 37, 201, 50, 128, 140, 213, 201, 207, 186, 70, 172, 227, 121, 174, 42, 209, 16, 207, 179, 158, 128, 185, 240, 3, 0, 8, 0, 1, 70, 204, 1, 159, 169, 39, 9, 157, 149, 70, 176, 88, 226, 249, 94, 203, 19, 223, 38, 123, 156, 224, 100, 248, 44, 93, 211, 101, 226, 86, 33, 169, 1, 0, 0, 0, 107, 72, 48, 69, 2, 33, 0, 170, 37, 93, 202, 126, 108, 62, 136, 64, 177, 3, 218, 88, 225, 249, 17, 36, 41, 247, 183, 250, 162, 146, 10, 36, 27, 174, 154, 41, 126, 96, 9, 2, 32, 4, 101, 193, 63, 219, 87, 68, 206, 228, 247, 51, 169, 125, 147, 39, 99, 16, 179, 155, 108, 221, 53, 204, 70, 131, 159, 184, 216, 139, 71, 41, 94, 1, 33, 2, 7, 243, 140, 164, 118, 180, 192, 80, 16, 157, 224, 180, 245, 253, 204, 217, 131, 2, 68, 205, 48, 199, 157, 125, 31, 247, 218, 81, 12, 143, 12, 23, 255, 255, 255, 255, 2, 192, 207, 106, 0, 0, 0, 0, 0, 2, 106, 0, 248, 81, 42, 44, 0, 0, 0, 0, 25, 118, 169, 20, 118, 131, 181, 173, 30, 159, 105, 113, 125, 94, 81, 192, 92, 61, 211, 52, 138, 3, 118, 249, 136, 172, 0, 0, 0, 0, 36, 1, 1, 192, 207, 106, 0, 0, 0, 0, 0, 25, 118, 169, 20, 178, 249, 58, 6, 19, 202, 102, 161, 91, 215, 62, 18, 14, 22, 114, 140, 80, 203, 63, 57, 136, 172, 0, 0, 65, 32, 154, 5, 72, 58, 206, 55, 214, 19, 3, 182, 90, 52, 2, 236, 145, 0, 27, 234, 85, 213, 223, 30, 238, 236, 4, 183, 38, 60, 130, 164, 179, 157, 24, 120, 229, 106, 155, 71, 163, 179, 48, 195, 164, 42, 23, 142, 4, 210, 60, 16, 53, 82, 138, 51, 96, 254, 117, 249, 117, 90, 36, 154, 229, 197, 25, 176, 85, 106, 143, 230, 125, 49, 118, 169, 38, 169, 129, 181, 116, 99, 33, 12, 44, 230, 167, 52, 232, 148, 159, 192, 28, 153, 13, 85, 48, 107]","st_hash":"01a458d2b555c9094b5e2d0cd24f682b79e72d85083e4a9a5656a8287c0033fe"},"target":"drive_abci::execution::platform_events::state_transition_processing::process_raw_state_transitions::v0","span":{"endpoint":"PrepareProposal","height":252303,"request_id":"8bb3175d-648e-4e34-bc55-6153fdf1a4ee","round":0,"name":"abci"},"spans":[{"endpoint":"PrepareProposal","height":252303,"request_id":"8bb3175d-648e-4e34-bc55-6153fdf1a4ee","round":0,"name":"abci"}],"threadName":"main","threadId":"ThreadId(1)"}

### PR DESCRIPTION
**Pull request by pauldelucia**
We added ENCRYPTION and DECRYPTION keys bound to Dashpay contract to default keys when registering a new identity through DET so that we could sign contactRequest documents. But we were supposed to bind to `contactRequest` document type. This uses `ContractBounds::SingleContractDocumentType` rather than `ContractBounds::SingleContract`, so the validation against the dashpay contract was causing identity registration to fail.

### CODE REVIEW

File: src/ui/identities/add_new_identity_screen/mod.rs [hunk 1]
```diff
@@ -1353,3 +1311,246 @@ impl ScreenLike for AddNewIdentityScreen {
...
+/// - AUTHENTICATION CRITICAL: General platform operations (actions should require PIN)
+/// - AUTHENTICATION HIGH: General platform operations
+/// - TRANSFER CRITICAL: Credit transfers
+/// - ENCRYPTION MEDIUM with DashPay contactRequest bounds: For contact requests per DIP-15
+/// - DECRYPTION MEDIUM with DashPay contactRequest bounds: For contact requests per DIP-15
+///
+/// Note: ENCRYPTION and DECRYPTION keys must use `SingleContractDocumentType` with "contactRequest"
+/// document type, not just `SingleContract`. The platform requires encryption key bounds to specify
+/// the exact document type for proper validation.
+pub fn default_identity_key_specs(
```
Comment (lklimek) [inline src/ui/identities/add_new_identity_screen/mod.rs:1327]: can we validate the state transition before sending, so that the user will get alert if it's invalid? I mean, the user can modify keys in advanced mode, so we might want to check if these modifications lead to correct state transition before we take funds from his core wallet, etc.

Comment (pauldelucia) [reply src/ui/identities/add_new_identity_screen/mod.rs:1327]: Yeah I think we can just disable selectors for example if they choose Transfer key, lock the security level to Critical.

Comment (pauldelucia) [reply src/ui/identities/add_new_identity_screen/mod.rs:1327]: For another PR
